import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Color Picker",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<meta
				name='google-site-verification'
				content='rGlUF3MJsyencVvNkeAhnJCe60VjDHQ_4MWMLBwazB0'
			/>
			<meta
				name='google-site-verification'
				content='s0Q1bOLR0q9AWm46PkecHOzV5EKZwNLphwqWfq-UsGo'
			/>
			<body>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
